from libqtile.config import Group, Match

class Groups(object):
    groups = [
        # first group that hold the terminals
        Group(
            label=' Terminal',
            init=True,
            exclusive=False,
            persist=False,
            matches=[Match(wm_class=['Alacritty', 'kitty'])],
            position=1,
            screen_affinity=1,
            name='1',
        ),
        Group(
            label=' Editor',
            init=True,
            exclusive=False,
            persist=False,
            matches=[Match(wm_class=['Code'])],
            position=2,
            screen_affinity=1,
            name='2',
        ),
        Group(
            label=' Files',
            init=True,
            exclusive=False,
            persist=False,
            matches=[Match(wm_class=['Nemo'])],
            position=3,
            screen_affinity=1,
            name='3',
        ),
        Group(
            label=' Graphics',
            init=True,
            exclusive=False,
            persist=False,
            matches=[Match(wm_class=['Nemo'])],
            position=4,
            screen_affinity=1,
            name='4',
        ),
        Group(
            label='ﱘ Music',
            init=True,
            exclusive=False,
            persist=False,
            matches=[Match(wm_class=['Nemo'])],
            position=5,
            screen_affinity=1,
            name='5',
        ),
        Group(
            label=' WebBrowser',
            init=True,
            persist=False,
            exclusive=False,
            matches=[Match(wm_class=['firefox'], role=['browser'])],
            position=6,
            screen_affinity=2,
            name='6',
        ),
        Group(
            label=' Mail',
            init=True,
            persist=False,
            exclusive=False,
            #   matches=[Match(wm_class=['firefox'])],
            position=7,
            screen_affinity=2,
            name='7',
        ),
        Group(
            label='調 Games',
            init=True,
            persist=False,
            exclusive=False,
            #   matches=[Match(wm_class=['firefox'])],
            position=8,
            screen_affinity=2,
            name='8',
        ),
        Group(
            label=' Chat',
            init=True,
            persist=False,
            exclusive=False,
            #   matches=[Match(wm_class=['firefox'])],
            position=9,
            screen_affinity=2,
            name='9',
        ),
        Group(
            label=' Settings',
            init=True,
            persist=False,
            exclusive=False,
            matches=[Match(wm_class=['PkgBrowser'])],
            position=10,
            screen_affinity=2,
            name='0',
        ),
    ]
