#!/usr/bin/env bash
#-*-coding:utf-8 -*-
#Auto updated?
#   Yes
#File:
#   autostart
#Author:
#   The-Repo-Club [wayne6324@gmail.com]
#Github:
#   https://github.com/The-Repo-Club/
#
#Created:
#   Sat 15 October 2022, 09:01:26 PM [GMT+1]
#Modified:
#   Sun 16 October 2022, 02:52:53 PM [GMT+1]
#
#Description:
#   Config for herbstluftwm
#
#Dependencies:
#   bash, herbstluftwm
#
# shellcheck disable=all

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#000000'
hc attr theme.active.border_width 10
hc attr theme.active.inner_width 1
hc attr theme.active.outer_width 4
hc attr theme.active.outer_color '#005f87'

hc attr theme.normal.color '#242424'
hc attr theme.normal.border_width 10
hc attr theme.normal.inner_width 1

hc attr theme.urgent.color orange
hc attr theme.inner_color '#ffffff'

hc attr theme.floating.border_width 10
hc attr theme.floating.outer_width 4
hc attr theme.floating.outer_color '#5f875f'
hc attr theme.floating.inner_width 1

hc set window_gap 2
hc set frame_padding 0
hc set smart_window_surroundings true
hc set smart_frame_surroundings false
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 0
hc set focus_follows_mouse 1
